# Generated by Django 3.1.7 on 2021-03-31 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('ListingId', models.AutoField(primary_key=True, serialize=False)),
                ('ListingName', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=500)),
                ('PhotoFileName', models.CharField(max_length=100)),
            ],
        ),
    ]
